import api from './api'
export const getMenuItems = (params) => api.get('/menu', { params })
export const getMenuItem = (slug) => api.get(`/menu/${slug}`)
export const createMenuItem = (data) => api.post('/menu', data)
export const updateMenuItem = (id, data) => api.put(`/menu/${id}`, data)
export const deleteMenuItem = (id) => api.delete(`/menu/${id}`)
export const toggleAvailable = (id) => api.patch(`/menu/${id}/toggle`)
export const reportOutOfStock = (itemId, message) => api.post('/menu/report-out-of-stock', { itemId, message })
export const getCategories = () => api.get('/categories')
export const createCategory = (data) => api.post('/categories', data)